name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP 8.3 and required extensions
        run: |
          sudo apt update
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt install -y php8.3 php8.3-cli php8.3-fpm php8.3-mbstring php8.3-bcmath php8.3-intl php8.3-gd php8.3-mysql php8.3-xml git

      - name: Install Node.js and NPM
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt install -y nodejs
          node -v
          npm -v

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install --prefer-dist --no-dev --optimize-autoloader

      - name: Configure SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_thy
          chmod 600 ~/.ssh/id_thy

      - name: Add SSH key to agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_thy

      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_thy -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PATH: /var/www/thy/thernthy.site
          NGINX_SERVICE: nginx
          PHP_SERVICE: php8.3-fpm
        run: |
          echo "VPS_PATH is set to: $VPS_PATH"
          ssh -i ~/.ssh/id_thy -o StrictHostKeyChecking=no -o BatchMode=yes $VPS_USER@$VPS_HOST << EOF
          set -e

          export VPS_PATH="${{ env.VPS_PATH }}"
          export NGINX_SERVICE="${{ env.NGINX_SERVICE }}"
          export PHP_SERVICE="${{ env.PHP_SERVICE }}"

          echo "VPS_PATH inside SSH session: $VPS_PATH"
          if [ -z "$VPS_PATH" ]; then
              echo "Error: VPS_PATH is empty"
              exit 1
          fi

          cd "$VPS_PATH" || { echo "Error: $VPS_PATH does not exist"; exit 1; }

          if [ ! -d ".git" ]; then
              echo "Error: $VPS_PATH is not a Git repository"
              exit 1
          fi

          git fetch --all
          git reset --hard origin/main

          composer install --prefer-dist --no-dev --optimize-autoloader
          composer require irazasyed/telegram-bot-sdk
          php artisan install:broadcasting
          composer require laravel/reverb
          php artisan reverb:install
          composer require pusher/pusher-php-server

          php artisan migrate --force

          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:clear
          php artisan view:cache

          npm ci
          npm run build

          chown -R www-data:www-data storage bootstrap/cache
          chmod -R 775 storage bootstrap/cache

          sudo systemctl restart "$NGINX_SERVICE"
          sudo systemctl restart "$PHP_SERVICE"

          echo "Deployment complete!"
          EOF
